"""Phase 4 — export the trained model into C headers for the ESP32 firmware.

microWakeWord produces a *streaming* `.tflite` plus a `.json` manifest. ESPHome
ships these as a model file; a standalone Arduino/PlatformIO firmware needs them
as C arrays, so we `xxd`-style encode them into headers consumed by
`ESP32HomeAssistant`'s WakeWordEngine.

Outputs (into ../echo-devices/libs/ESP32HomeAssistant/model/):
    model_charlie_data.h        // streaming wake-word model
    preprocessor_charlie_data.h // shared audio->log-mel frontend (if present)
    charlie_model_config.h      // manifest constants (window size, cutoff, …)

Usage:
    python3 training/export_headers.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "output"
MODEL_DIR = ROOT.parent / "echo-devices" / "libs" / "ESP32HomeAssistant" / "model"
MODEL_NAME = "charlie"


def _to_c_array(path: Path, symbol: str) -> str:
    data = path.read_bytes()
    lines = [
        "// Auto-generated by wakeword/training/export_headers.py — do not edit.",
        f"// Source: {path.name} ({len(data)} bytes)",
        "#pragma once",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        f"alignas(16) const unsigned char {symbol}[] = {{",
    ]
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append(f"const unsigned int {symbol}_len = {len(data)};")
    lines.append("")
    return "\n".join(lines)


def _find(name: str) -> Path | None:
    for pattern in (name, f"*{name}*"):
        hits = sorted(OUTPUT.glob(pattern))
        if hits:
            return hits[0]
    return None


def main() -> None:
    MODEL_DIR.mkdir(parents=True, exist_ok=True)

    model = OUTPUT / f"{MODEL_NAME}.tflite"
    if not model.exists():
        hits = sorted(OUTPUT.glob("*.tflite"))
        if not hits:
            raise SystemExit(f"[export] no .tflite found in {OUTPUT} — run stage3-train first")
        model = hits[0]
    print(f"[export] model: {model.name} ({model.stat().st_size} bytes)")

    # Streaming wake-word model
    (MODEL_DIR / "model_charlie_data.h").write_text(_to_c_array(model, "model_charlie_tflite"))
    print("[export] model_charlie_data.h")

    # Shared preprocessor model (raw PCM -> 40-ch log-mel)
    pre = _find("preprocessor.tflite") or _find("preprocessor")
    if pre and pre.resolve() != model.resolve():
        (MODEL_DIR / "preprocessor_charlie_data.h").write_text(
            _to_c_array(pre, "preprocessor_charlie_tflite")
        )
        print(f"[export] preprocessor_charlie_data.h ({pre.name})")
    else:
        print("[export] WARNING: no preprocessor.tflite found — the firmware will need the "
              "bundled frontend or a preprocessor model in output/")

    # Manifest constants
    manifest = model.with_suffix(".tflite.json")
    if not manifest.exists():
        manifest = OUTPUT / f"{MODEL_NAME}.json"
    micro: dict = {}
    if manifest.exists():
        raw = json.loads(manifest.read_text())
        micro = raw.get("micro", {}) or {}
        print(f"[export] manifest: {manifest.name}")

    config = [
        "// Auto-generated by wakeword/training/export_headers.py — do not edit.",
        "#pragma once",
        "",
        f"#define WW_FEATURE_STEP_SIZE   {int(micro.get('feature_step_size', 10))}",
        f"#define WW_SLIDING_WINDOW_SIZE {int(micro.get('sliding_window_size', 5))}",
        f"#define WW_TENSOR_ARENA_SIZE   {int(micro.get('tensor_arena_size', 26080))}",
        f"#define WW_PROBABILITY_CUTOFF  {float(micro.get('probability_cutoff', 0.97)):.2f}f",
        "",
        f"#define WW_MODEL_NAME         \"{MODEL_NAME}\"",
        "",
    ]
    (MODEL_DIR / "charlie_model_config.h").write_text("\n".join(config))
    print("[export] charlie_model_config.h")


if __name__ == "__main__":
    main()
