# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egrpc_api.proto\x12\x03\x61pi\"6\n\x0bToolRequest\x12\x10\n\x08toolName\x18\x01 \x01(\t\x12\x15\n\rargumentsJson\x18\x02 \x01(\t\"3\n\x0cToolResponse\x12\x12\n\nresultJson\x18\x01 \x01(\t\x12\x0f\n\x07isError\x18\x02 \x01(\x08\x32=\n\nMCPService\x12/\n\x08\x43\x61llTool\x12\x10.api.ToolRequest\x1a\x11.api.ToolResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOOLREQUEST']._serialized_start=23
  _globals['_TOOLREQUEST']._serialized_end=77
  _globals['_TOOLRESPONSE']._serialized_start=79
  _globals['_TOOLRESPONSE']._serialized_end=130
  _globals['_MCPSERVICE']._serialized_start=132
  _globals['_MCPSERVICE']._serialized_end=193
# @@protoc_insertion_point(module_scope)
