# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_api_pb2 as grpc__api__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpc_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MCPServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallTool = channel.unary_unary(
                '/api.MCPService/CallTool',
                request_serializer=grpc__api__pb2.ToolRequest.SerializeToString,
                response_deserializer=grpc__api__pb2.ToolResponse.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/api.MCPService/ListTools',
                request_serializer=grpc__api__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=grpc__api__pb2.ListToolsResponse.FromString,
                _registered_method=True)


class MCPServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CallTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MCPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CallTool,
                    request_deserializer=grpc__api__pb2.ToolRequest.FromString,
                    response_serializer=grpc__api__pb2.ToolResponse.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=grpc__api__pb2.ListToolsRequest.FromString,
                    response_serializer=grpc__api__pb2.ListToolsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.MCPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.MCPService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MCPService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.MCPService/CallTool',
            grpc__api__pb2.ToolRequest.SerializeToString,
            grpc__api__pb2.ToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.MCPService/ListTools',
            grpc__api__pb2.ListToolsRequest.SerializeToString,
            grpc__api__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
