services:
    api:
        build: ./nodejs-apis
        container_name: charlie-api
        profiles: ['cpu', 'gpu']
        environment:
            - NODE_ENV=production
            - PULSE_SERVER=unix:/tmp/pulse/native
        volumes:
            - ./nodejs-apis/src:/app/src
            - ./nodejs-apis/.env:/app/.env
            - ./nodejs-apis/tsconfig.json:/app/tsconfig.json
            - ~/media/musics:/musics
            - ${XDG_RUNTIME_DIR}/pulse/native:/tmp/pulse/native
            - ./nodejs-apis/recordings:/app/recordings
            - ./echo-devices:/echo-devices
        ports:
            - '9300:9300' # http server
            - '9303:9303' # audio udp
            - '9304:9304' # mqtt server
        command: 'yarn start'
        depends_on:
            - db
        restart: unless-stopped
        networks:
            - internal
    network-scanner:
        build: ./network-scanner
        container_name: charlie-network-scanner
        profiles: ['cpu', 'gpu']
        environment:
            - NODE_ENV=production
        volumes:
            - ./network-scanner/src:/app/src
        ports:
            - '9306:9306'
        command: 'yarn start'
        restart: unless-stopped
        network_mode: host
    ai-agents:
        build: ./python-apis
        profiles: ['cpu']
        container_name: charlie-ai-agents
        ports:
            - '9301:8000'
        volumes:
            - ./python-apis/app:/app
            - ./nodejs-apis:/mcp-server
            - ./python-apis/qwen_models:/models
        environment:
            - PYTHONUNBUFFERED=1
            - MISTRAL_API_KEY=${MISTRAL_API_KEY}
            - SSE_HOST=http://${SSE_HOST}:9300/sse
            - STT_LANGUAGE=${STT_LANGUAGE}
            - LOAD_STT_MODEL=${LOAD_STT_MODEL}
            - LLM_MODEL=${LLM_MODEL}
        restart: unless-stopped
        networks:
            - internal
    ai-agents-gpu:
        build: ./python-apis/Dockerfile.gpu
        container_name: charlie-ai-agents-gpu
        profiles: ['gpu']
        ports:
            - '9301:8000'
        volumes:
            - ./python-apis/app:/app
            - ./nodejs-apis:/mcp-server
            - ./python-apis/qwen_models:/models
        environment:
            - PYTHONUNBUFFERED=1
            - MISTRAL_API_KEY=${MISTRAL_API_KEY}
            - SSE_HOST=http://${SSE_HOST}:9300/sse
            - STT_LANGUAGE=${STT_LANGUAGE}
            - LOAD_STT_MODEL=${LOAD_STT_MODEL}
            - LLM_MODEL=${LLM_MODEL}
        restart: unless-stopped
        networks:
            - internal
        #devices:
        #    - /dev/dri:/dev/dri
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
    db:
        container_name: charlie-db
        profiles: ['cpu', 'gpu']
        image: mongo
        ports:
            - '9302:27017'
        restart: unless-stopped
        volumes:
            - ./db:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=
            - MONGO_INITDB_ROOT_PASSWORD=
        networks:
            - internal
    frontend:
        build: ./frontend
        container_name: charlie-frontend
        profiles: ['cpu', 'gpu']
        environment:
            - NODE_ENV=production
            - API_HOST=http://api:9300
        volumes:
            - ./frontend/src:/app/src
            - ./frontend/.env:/app/.env
            - ./frontend/vite.config.js:/app/vite.config.js
            - ./frontend/public:/app/public
            - ./certs:/certs
        ports:
            - '9305:3000'
        command: 'yarn start --host'
        depends_on:
            - api
        restart: unless-stopped
        networks:
            - internal

networks:
    internal:
        driver: bridge
    charlieExternal:
        external: true
