### ask
POST http://localhost:8000/ask
Content-Type: application/json

{
    "question": "Envoi moi par email une recette simple de pate carbonara"
}


### tts
POST http://localhost:8000/tts
Content-Type: application/json
Accept: audio/wav

{
    "text": "Salut"
}